export const MENU_ITEMS = [
  {
    id: 'series-a-seekh',
    emoji: '\u{1F959}',
    name: 'The Series A Seekh Kebab Roll',
    price: '$4.20M (pre-revenue)',
    subtitle: 'Pre-money valuation: delicious',
    spice: 3,
  },
  {
    id: 'pivot-paneer',
    emoji: '\u{1FAD3}',
    name: 'Pivot Paneer Tikka Roll',
    price: '2 SAFE notes',
    subtitle: 'We were a SaaS company once',
    spice: 2,
  },
  {
    id: 'burn-rate-bhurji',
    emoji: '\u{1F373}',
    name: 'The Burn Rate Bhurji Roll',
    price: '$0 (bootstrapped)',
    subtitle: 'Consuming capital, one bite at a time',
    spice: 4,
  },
  {
    id: 'yc-chicken-tikka',
    emoji: '\u{1F357}',
    name: 'YC Chicken Tikka Roll',
    price: '$500K (standard deal)',
    subtitle: 'Backed by garlic chutney',
    spice: 3,
  },
  {
    id: 'cap-table-kathi',
    emoji: '\u{1F32F}',
    name: 'Cap Table Kathi Roll',
    price: '409A pending',
    subtitle: 'Ownership is complicated',
    spice: 2,
  },
  {
    id: 'runway-raita',
    emoji: '\u{1F963}',
    name: 'Runway Extension Raita',
    price: 'Free (angel round)',
    subtitle: "It's a side. Like your consulting gig.",
    spice: 0,
  },
];
