// packages/shared/lib/types/rover-feedback.ts
//
// Real-time user-feedback ("steering") channel types. The visitor can submit
// guidance during a running task; the worker drains items at each planner
// iteration boundary, injects them into the LLM prompt as per-step feedback,
// and emits ack events back so the UI can mark each item Applied vs Dropped.

export type RoverFeedbackSource = 'text' | 'voice';

export type RoverFeedbackDropReason =
  | 'run_ended'
  | 'run_canceled'
  | 'run_id_mismatch'
  | 'queue_full'
  | 'empty_text';

export interface RoverUserFeedback {
  /** ULID generated by the SDK at submission; round-trips through ack events. */
  id: string;
  /** The run this item is scoped to. Cross-run delivery is rejected. */
  runId: string;
  /** Visitor text, already trimmed by the UI; the worker re-sanitizes before LLM injection. */
  text: string;
  /** Whether this came from typing or voice dictation. Telemetry only. */
  source: RoverFeedbackSource;
  /** Client epoch ms at submission. */
  submittedAt: number;
}

export interface RoverFeedbackApplied {
  /** Batched — multiple items may drain into the same planner iteration. */
  ids: string[];
  /** Index in agentPrevSteps where the items were attached. */
  appliedAtStepIndex: number;
  runId: string;
}

export interface RoverFeedbackDropped {
  ids: string[];
  runId: string;
  reason: RoverFeedbackDropReason;
}
